package com.pa.ipv01.resource;

public class VanKhanDetailres {

	public static final String[] vkresource = { VanKhanres.thammo,
			VanKhanres.chuyennha, VanKhanres.letang, VanKhanres.totien,
			VanKhanres.tienchu, VanKhanres.thanhsu, VanKhanres.thanhhoang,
			VanKhanres.thocong, VanKhanres.thantai, VanKhanres.thanlinh,
			VanKhanres.tatnien, VanKhanres.mieu, VanKhanres.chuakho,
			VanKhanres.chua, VanKhanres.m1nram, VanKhanres.thuong,
			VanKhanres.thuongtho, VanKhanres.tangia, VanKhanres.giatien,
			VanKhanres.ta, VanKhanres.phat, VanKhanres.lephat22,
			VanKhanres.ongtao, VanKhanres.nhaptrach, VanKhanres.lemochap,
			VanKhanres.cuahang, VanKhanres.diamach, VanKhanres.gtngoai,
			VanKhanres.gttrong, VanKhanres.thanhtran, VanKhanres.thanhhien,
			VanKhanres.quanam, VanKhanres.uminh, VanKhanres.dongtho,
			VanKhanres.cuoiga, VanKhanres.cung, VanKhanres.benhtat,
			VanKhanres.giaihan, VanKhanres.chungsinh, VanKhanres.cautu,
			VanKhanres.congdong, VanKhanres.giohet, VanKhanres.giodau,
			VanKhanres.ttdangle, VanKhanres.thanhminh, VanKhanres.trungthu,
			VanKhanres.trungnguyen, VanKhanres.trunguyen1, VanKhanres.hanthuc,
			VanKhanres.hanguyen, VanKhanres.doanngo, VanKhanres.nguyentieu,
			VanKhanres.ledang, VanKhanres.cungmu, };
	public static final String[] vankhanUrl = {
			"file:///android_asset/vankhan_1.html",
			"file:///android_asset/vankhan_2.html",
			"file:///android_asset/vankhan_3.html",
			"file:///android_asset/vankhan_4.html",
			"file:///android_asset/vankhan_5.html",
			"file:///android_asset/vankhan_6.html",
			"file:///android_asset/vankhan_7.html",
			"file:///android_asset/vankhan_8.html",
			"file:///android_asset/vankhan_9.html",
			"file:///android_asset/vankhan_10.html",
			"file:///android_asset/vankhan_11.html",
			"file:///android_asset/vankhan_12.html",
			"file:///android_asset/vankhan_13.html",
			"file:///android_asset/vankhan_14.html",
			"file:///android_asset/vankhan_15.html",
			"file:///android_asset/vankhan_16.html",
			"file:///android_asset/vankhan_17.html",
			"file:///android_asset/vankhan_18.html",
			"file:///android_asset/vankhan_19.html",
			"file:///android_asset/vankhan_20.html",
			"file:///android_asset/vankhan_21.html",
			"file:///android_asset/vankhan_22.html",
			"file:///android_asset/vankhan_23.html",
			"file:///android_asset/vankhan_24.html",
			"file:///android_asset/vankhan_25.html",
			"file:///android_asset/vankhan_26.html",
			"file:///android_asset/vankhan_27.html",
			"file:///android_asset/vankhan_28.html",
			"file:///android_asset/vankhan_29.html",
			"file:///android_asset/vankhan_30.html",
			"file:///android_asset/vankhan_31.html",
			"file:///android_asset/vankhan_32.html",
			"file:///android_asset/vankhan_33.html",
			"file:///android_asset/vankhan_34.html",
			"file:///android_asset/vankhan_35.html",
			"file:///android_asset/vankhan_36.html",
			"file:///android_asset/vankhan_37.html",
			"file:///android_asset/vankhan_38.html",
			"file:///android_asset/vankhan_39.html",
			"file:///android_asset/vankhan_40.html",
			"file:///android_asset/vankhan_41.html",
			"file:///android_asset/vankhan_42.html",
			"file:///android_asset/vankhan_43.html",
			"file:///android_asset/vankhan_44.html",
			"file:///android_asset/vankhan_45.html",
			"file:///android_asset/vankhan_46.html",
			"file:///android_asset/vankhan_47.html",
			"file:///android_asset/vankhan_48.html",
			"file:///android_asset/vankhan_49.html",
			"file:///android_asset/vankhan_50.html",
			"file:///android_asset/vankhan_51.html",
			"file:///android_asset/vankhan_52.html",
			"file:///android_asset/vankhan_53.html",
			"file:///android_asset/vankhan_54.html", };

}
